version: 2

sources:
  - name: raw
    database: data-the-information-lab  
    schema: the_information_lab_dataset  
    tables:
      - name: raw_orders
      - name: raw_customers
      - name: raw_orders_items
      - name: raw_products